package com.university.enums.payloads;

public enum PostBackPayloads {
    GET_STARTED_PAYLOAD,
    HEAD_OF_THE_DEPARTMENT_PAYLOAD,
    DEPARTMENT_STATISTIC_PAYLOAD,
    AVG_SALARY_PAYLOAD,
    COUNT_OF_EMPLOYEE_PAYLOAD,
    GLOBAL_SEARCH_PAYLOAD
}
